# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44ed4066e02f5ac1ca6b4b67378ec116fd1ab783bcefa61e59a89b43ccd3d4e804fcf4981b1ba528506221598f2fb5dd9480a85c4a1051227db9b0a73506b03d

test:
  secret_key_base: f3ecc79a324749c77d8d016071846e0514d5769da6ad94924c7cc8879e59bb919b14db4d5e4ead06414ca79283e718b23de674160833654715ddd8612864d68c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
